---
- name: Check if docker is already installed.
  command: 'which docker'
  register: docker_exists_result
  failed_when: false
  changed_when: false

- name: Download Docker installation file.
  get_url:
    url: https://get.docker.com
    dest: ./get-docker.sh
    mode: '0775'
  when: docker_exists_result.rc == 1

- name: Install Docker.
  command: ./get-docker.sh
  when: docker_exists_result.rc == 1     

- name: Delete Docker installation file.
  file:
    path: ./get-docker.sh
    state: absent

- name: Ensures Docker is started and enabled at booth.
  service:
    name: docker
    state: started
    enabled: true
  
- name: Add users to Docker group.
  user:
    name: "{{ item }}"
    state: present
    groups:
      - docker
    append: true
  with_items: "{{ docker_users }}"  

- name: Install docker python package.
  pip:
    name: docker
    
- name: Install docker compose.
  pip:
    name: docker-compose
    state: present
    executable: "{{ pip_version }}"
  when: install_docker_compose | bool

# allows containers to see url address of localhost
- name: Create docker config directory.
  file:
    path: "/etc/docker"
    state: directory
    mode: '0755'

- name: Create docker daemon configuration file.
  notify: restart docker
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"


