galaxy_info:
  author: ellolo
  role_name: docker_influxdb_grafana 
  description: Setup Influxdb and grafana services. 
  license: license (MIT)
  min_ansible_version: 2.9
  galaxy_tags:
    - influx
    - influxdb
    - grafana      
  dependencies: []
