---
# users to add to docker group
docker_users:
  - ansible

# IP of DNS in local network
private_network_dns: "192.168.178.1"

# pip version to use to install docker compose
pip_version: pip3

# if to install docker compose
install_docker_compose: false
