---
- name: Check if docker is already installed.
  command: 'which docker'
  register: docker_exists_result
  ignore_errors: True
  changed_when: False

- name: Download Docker installation file.
  get_url:
    url: https://get.docker.com
    dest: ./get-docker.sh
    mode: '0775'
  when: docker_exists_result.rc == 1

- name: Install Docker.
  command: ./get-docker.sh
  when: docker_exists_result == 1     

- name: Delete Docker installation file.
  file:
    path: ./get-docker.sh
    state: absent

- name: Ensures Docker is started and enabled at booth.
  service:
    name: docker
    state: started
    enabled: yes   
  
- name: Add users to Docker group.
  user:
    name: "{{ item }}"
    state: present
    group: docker
    append: True
  with_items: "{{ docker_users }}"

- name: Install docker compose.
  pip:
    name: docker-compose
    state: present
    executable: "{{ pip_version }}"
  when: install_docker_compose | bool
