---
- name: Starts grafana container.
  docker_container:
    name: grafana-monitoring
    image: grafana/grafana
    state: started
    restart_policy: "{{ grafana_restart_policy }}"
    ports:
      - 3000:3000
    env:
        GF_SECURITY_ADMIN_USER: "{{ grafana_admin_user }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_pwd }}"
        GF_SECURITY_ALLOW_EMBEDDING: "{{ grafana_allow_embedding }}"
        GF_AUTH_ANONYMOUS_ENABLED: "{{ grafana_auth_anon_enable }}"
        GF_PANELS_DISABLE_SANITIZE_HTML: "{{ grafana_disable_sanitized_html }}"
        GF_ANALYTICS_REPORTING_ENABLED: "{{ grafana_reporting_enabled }}"
    networks:
      - name: "{{ monitoring_network }}"
    purge_networks: yes     
    volumes:
      - "{{ grafana_data_volume }}:/var/lib/grafana:rw"
