---
- name: Start influxdb container.
  docker_container:
    name: influxdb-monitoring
    image: influxdb
    state: started
    restart_policy: "{{ influxdb_restart_policy }}"
    ports:
      - 8086:8086
    networks:
      - name: "{{ monitoring_network }}"
        aliases: "{{ influxdb_address }}"
    purge_networks: yes    
    volumes:
      - "{{ influxdb_conf_dir }}/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
      - "{{ influxdb_data_volume }}:/var/lib/influxdb"

