---
- name: create docker registry directory.
  file:
    path: "{{ docker_registry_dir }}"
    state: directory
    mode: '0755'
  when: inventory_hostname in groups["docker_registry"]

- name: remove pre-existing insecure registry url entry in docker daemon config.
  notify: restart docker
  lineinfile:
    path: "/etc/docker/daemon.json"
    regexp: "^\t\"insecure-registries"
    state: absent

- name: add insecure registry url to docker daemon config.
  notify: restart docker
  lineinfile:
    path: "/etc/docker/daemon.json"
    insertafter: "^\\{"
    firstmatch: yes
    line: "\t\"insecure-registries\" : [\"{{ docker_registry_url }}\"],"
    state: present

- meta: flush_handlers

- name: ensure docker registry is running.
  docker_container:
    name: docker-registry
    image: registry:2
    state: started
    restart_policy: "{{ docker_registry_restart_policy }}"
    ports:
      - 5000:5000
    volumes:
      - "{{ docker_registry_dir }}:/var/lib/registry"
  when: inventory_hostname in groups["docker_registry"]


